CREATE TYPE genere_list AS ENUM (
    'Mystery',
    'Biography',
    'Non-Fiction',
    'Reference',
    'Fiction',
    'Textbook',
    'Political',
    'Religious'
);

CREATE TABLE library (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    author TEXT NOT NULL,
    genere genere_list NOT NULL,
    completed BOOLEAN DEFAULT false,
    lent BOOLEAN DEFAULT false
); 